spring:
  profiles:
    active: local
  # ?? ??? ?? ????
  web:
    resources:
      add-mappings: false
  jpa:
    # ??? ???? view ???? ???? ??
    open-in-view: false # https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.data.spring.jpa.open-in-view
    # Hibernate? ???? ?? ???? ?? ??
    generate-ddl: false
    hibernate:
      # Hibernate? ??? ??/??/???? ?? : ???? ??
      ddl-auto: none
    # ?? SQL ?? ??
    show-sql: false
    properties:
      hibernate:
        # ?? ?? ?? ?? ??
        query:
          # ??? ??? ?? ?? ?? ??
          plan_cache_max_size: 512 #https://medium.com/javarevisited/troubleshooting-and-fixing-outofmemoryerror-in-spring-boot-5cc559f556ea
          plan_parameter_metadata_max_size: 32
          # In ? ???? ?? ???? ? ?? ???? ??? ?? ??
          # where id in (?, ?, ?, ?) ?? ??? ???? ??
          in_clause_parameter_padding: true #https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html#configurations-query
        # Batch ??/?? ??(?? ??
        jdbc:
          # 500? ??? ??? JDBC? ? ?? ??
          batch_size: 500
          batch_versioned_data: true
        # ?? ???? ? ?? ??? ??
        order_inserts: true
        # ?? ???? ? ?? ??? ??
        order_updates: true
        # SQL ??? ??(??? ??)
        format_sql: true
        # Lazy Loading N+1? ???? ?? ??? ?? ?? ???
        default_batch_fetch_size: 500 #https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html#configurations-database-fetch
        # padded ??? : ?? ??? ?? ?? ?? ??
        batch_fetch_style: padded #https://docs.jboss.org/hibernate/orm/4.2/manual/en-US/html/ch20.html#performance-fetching-batch
  datasource:
    hikari:
      # MySQL ?? ??? ??
      data-source-properties:
        rewriteBatchedStatements: true
      # ??? ?? ??(idle) 10?
      idle-timeout: 10000
      # ??? ?? ??? ?? ??? ?? 10?
      connection-timeout: 10000
      # DB ?? ??? ?? 10?
      # ??? ??? ?? ???? ???? ????? 10? ?? ? ??
      validation-timeout: 10000

jasypt:
  encryptor:
    password: default